### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by lifehome**
Added a few sites and notes, rearranged the list in alphabetical order.

### CODE REVIEW

**Comment by benlau** [comment]
Please don't sort the list. I don't know what you have added / removed. I will check new site before approval, but now I can not judge it.

**Comment by lifehome** [comment]
Oh, sure, I'll restore the sortings then.

**Comment by lifehome** [comment]
@benlau The sorting is fixed, and the addition lines are shown clearly now.

**Comment by benlau** [comment]
Hi @lifehome ,

Thank you! However, I found that many sites are not accessible. For example,

authorizedprotect.xyz
bcrodriguezfollowrejuvenate.xyz
http://buzztopichk.com/
http://domesticlaboratory.faith/
http://friendshare.hk/
http://hkcoolshare.com/
http://hksnapshot.com/
http://hkupdates.com/
http://hottopics2know.com/
http://post4share.com/

(Stop checking at that point)

And this site is just a Ad only.
glimpseplay.faith

Where you found those sites?

**Comment by lifehome** [comment]
Those sites are found from some of my "content-farm die-hard fans" friend, who believes those sites are having various resources to gather news like that. :argh:

Some of them are IP restricted, I tested it from my home, my phone, and also some computers at Cafe and my company, the results are vary from normal 404 to different site content, I think it is zombie-domain that controlled by some guys to spread ads and use as mirror sites of content farm.

**Comment by lifehome** [comment]
Oh and BTW, some are not accessible with domain itself.

Those I tagged with "video share zombie-subdomains" are needed to check the subdomain "v.somedomain.tld", as apex domain are for other purposes I guess.

**Comment by benlau** [comment]
I see. hksnaptshot.com is fine. But for other sites that can not be verified. I can not add them. Could you remove it from the patch? 

p.s shareba.com is duplicated.

**Comment by lifehome** [comment]
Closing as the list maybe expired.

**Pull request closed without merging**
