### PR TITLE
Add a site into the list

### PR DESCRIPTION
**Pull request by CodeingBoy**
add guudo.cn into the list

### CODE REVIEW

**Comment by benlau** [comment]
Hi,

Thx for your submit. However, beside the guudo.cn , all other sites are mainly related to programming/development. Why you think we should consider as content farm and block them?

**Comment by CodeingBoy** [comment]
I think those are rubbish site.Their contents are copied from other site or automatically grub from Internet.So, when I develop a software, got an error, and search on Google, the search result contains many rubbish site.I click many times, but I only got same content.They wasted a lot of many time.
Probably I misunderstood what is the definition of Content Farmer, if it is, sorry first.Please point out my mistakes directly, I will remove those sites does not meet the standard.

**Comment by benlau** [comment]
I see. That is enough. A clear rules of blocking is not ready yet. I am still observing the reason why people hate them in order to build the rules. Plagiarism is definitely a reason to block them.

Thx.

**Comment by CodeingBoy** [comment]
You are welcome. :)

**Pull request merged**
